2018-06-05 18:28:19,673 ERROR: Exception on / [GET] [in /home/stive/blogpost/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/stive/Desktop/blogpost/app/main/routes.py", line 44, in index
    prev_url=prev_url)
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/stive/Desktop/blogpost/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/stive/Desktop/blogpost/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/home/stive/Desktop/blogpost/app/templates/base.html", line 13, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('blogpost.png') }}">Blogpost</a>
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/stive/blogpost/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'blogpost.png'. Did you mean 'auth.logout' instead?
2018-06-05 18:30:49,838 INFO: Blogpost startup [in /home/stive/Desktop/blogpost/app/__init__.py:72]
2018-06-05 18:32:26,347 INFO: Blogpost startup [in /home/stive/Desktop/blogpost/app/__init__.py:72]
2018-06-05 18:36:28,381 INFO: Blogpost startup [in /home/stive/Desktop/blogpost/app/__init__.py:72]
2018-06-05 18:37:08,857 INFO: Blogpost startup [in /home/stive/Desktop/blogpost/app/__init__.py:72]
2018-06-05 18:38:11,754 INFO: Blogpost startup [in /home/stive/Desktop/blogpost/app/__init__.py:72]
2018-06-05 18:42:39,300 INFO: Blogpost startup [in /home/stive/Desktop/blogpost/app/__init__.py:72]
2018-06-05 18:48:16,117 INFO: Blogpost startup [in /home/stive/Desktop/blogpost/app/__init__.py:72]
2018-06-05 19:03:21,169 INFO: Blogpost startup [in /home/stive/Desktop/blogpost/app/__init__.py:72]
